// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearInstallerBear.png
var resourceKrankyBearInstallerBearPngData []byte
var resourceKrankyBearInstallerBearPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearInstallerBear.png",
	StaticContent: resourceKrankyBearInstallerBearPngData,
}

//go:embed assets/images/KrankyBearInstallerBearFull.png
var resourceKrankyBearInstallerBearFullPngData []byte
var resourceKrankyBearInstallerBearFullPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearInstallerBearFull.png",
	StaticContent: resourceKrankyBearInstallerBearFullPngData,
}

//go:embed assets/images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}
